version: '3.9'


services:
  db:
    container_name: db
    image: postgres:14-alpine
    ports:
      - '5432:5432'

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

    volumes:
      - ./data/db:/var/lib/postgresql/data/

  frontend:
    build:
      context: ./todolist-app
      dockerfile: Dockerfile

    ports:
      - '80:3000'

    volumes:
      - ./todolist-app:/app/todolist-app

    depends_on:
      - backend

  backend: 
    container_name: backend
    build: 
      context: ./newdjangotodo
      dockerfile: Dockerfile

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

    ports:
      - '8000:8000'

    volumes:
      - ./newdjangotodo:/app/newdjangotodo

    depends_on:
      - db